tap "omnisharp/omnisharp-roslyn"

# The one true editor!
cask "emacs"

# Useful utilities
brew "readline"
brew "tree"
brew "rg"
brew "fd"

# Dev stuff
brew "git"
brew "openssl"
brew "omnisharp"
cask "java"
brew "git-credential-manager"
