tap "omnisharp/omnisharp-roslyn"

# The one true editor!
brew "emacs"

# Useful utilities
brew "readline"
brew "tree"

# Dev stuff
brew "git"
brew "omnisharp"
cask "java"
brew "git-credential-manager"
